// warehouse-area-calc/src/App.vue
<template>
  <div class="app-container">
    <header class="app-header">
      <div class="header-content">
        <div class="logo-area">
          <el-icon :size="32" color="#409eff"><OfficeBuilding /></el-icon>
          <div class="title">
            <h1>仓储面积测算工具</h1>
            <p>Warehouse Area Calculator</p>
          </div>
        </div>
        <div class="header-desc">
          智能测算仓储有效使用面积，辅助仓库布局优化设计
        </div>
      </div>
    </header>
    
    <main class="app-main">
      <el-row :gutter="20">
        <el-col :xs="24" :md="10" :lg="8" :xl="7" :xxl="6" class="col-form">
          <WarehouseForm :warehouse="warehouse" />
        </el-col>
        
        <el-col :xs="24" :md="14" :lg="16" :xl="17" :xxl="18" class="col-right">
          <el-row :gutter="20">
            <el-col :xs="24" :md="12">
              <ResultPanel
                :original-area="originalArea"
                :pillar-area="pillarArea"
                :aisle-area="aisleArea"
                :wall-margin-area="wallMarginArea"
                :effective-area="effectiveArea"
                :shelf-count="shelfCount"
                :space-utilization="spaceUtilization"
                :utilization-rate="utilizationRate"
              />
            </el-col>
            <el-col :xs="24" :md="12">
              <WarehouseVisual
                :warehouse="warehouse"
                :pillars="pillars"
                :shelves="shelves"
              />
            </el-col>
          </el-row>
          
          <el-row :gutter="20" class="row-compare">
            <el-col :span="24">
              <ComparePanel
                :warehouse="warehouse"
                :original-area="originalArea"
                :effective-area="effectiveArea"
                :shelf-count="shelfCount"
                :space-utilization="spaceUtilization"
                @apply-scheme="applyScheme"
              />
            </el-col>
          </el-row>
        </el-col>
      </el-row>
    </main>
    
    <footer class="app-footer">
      <p>© 2024 仓储面积测算工具 - 助力仓储物流数字化转型</p>
    </footer>
  </div>
</template>

<script setup>
import { OfficeBuilding } from '@element-plus/icons-vue'
import WarehouseForm from './components/WarehouseForm.vue'
import ResultPanel from './components/ResultPanel.vue'
import WarehouseVisual from './components/WarehouseVisual.vue'
import ComparePanel from './components/ComparePanel.vue'
import { useWarehouseCalc } from './composables/useWarehouseCalc'

const {
  warehouse,
  originalArea,
  pillarArea,
  aisleArea,
  wallMarginArea,
  effectiveArea,
  shelfCount,
  spaceUtilization,
  utilizationRate,
  pillars,
  shelves
} = useWarehouseCalc()

const applyScheme = (scheme) => {
  Object.assign(warehouse, scheme)
}
</script>

<style scoped>
.app-container {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  background: #f5f7fa;
}

.app-header {
  background: linear-gradient(135deg, #409eff 0%, #66b1ff 100%);
  color: white;
  padding: 24px 40px;
  box-shadow: 0 2px 12px rgba(64, 158, 255, 0.3);
}

.header-content {
  max-width: 1600px;
  margin: 0 auto;
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-wrap: wrap;
  gap: 16px;
}

.logo-area {
  display: flex;
  align-items: center;
  gap: 16px;
}

.title h1 {
  margin: 0;
  font-size: 24px;
  font-weight: 600;
}

.title p {
  margin: 4px 0 0 0;
  font-size: 13px;
  opacity: 0.9;
}

.header-desc {
  font-size: 14px;
  opacity: 0.95;
}

.app-main {
  flex: 1;
  padding: 24px 40px;
  max-width: 1600px;
  margin: 0 auto;
  width: 100%;
  box-sizing: border-box;
}

.col-form {
  margin-bottom: 20px;
}

.col-right {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.row-compare {
  margin-top: 0;
}

.app-footer {
  background: #303133;
  color: #909399;
  text-align: center;
  padding: 16px;
  font-size: 13px;
}

.app-footer p {
  margin: 0;
}

@media (max-width: 1200px) {
  .app-header,
  .app-main {
    padding: 20px;
  }
}

@media (max-width: 768px) {
  .header-content {
    flex-direction: column;
    align-items: flex-start;
  }
  
  .app-header,
  .app-main {
    padding: 16px;
  }
}
</style>

// sports-training-load-calc/src/App.svelte
<script>
  import TrainingForm from './components/TrainingForm.svelte'
  import ResultDisplay from './components/ResultDisplay.svelte'
  import { calculateTrainingLoad } from './lib/trainingLoad.js'
  
  let result = null
  let showResult = false
  
  function handleCalculate(formData) {
    result = calculateTrainingLoad(formData)
    showResult = true
  }
  
  function resetForm() {
    result = null
    showResult = false
  }
</script>

<div class="app">
  <header class="header">
    <div class="headerContent">
      <div class="logo">
        <span class="logoIcon">🏋️</span>
        <h1 class="title">运动训练负荷计算器</h1>
      </div>
      <p class="subtitle">科学评估训练强度，智能规划恢复方案</p>
    </div>
  </header>
  
  <main class="main">
    <div class="container">
      {#if !showResult}
        <div class="formSection">
          <div class="card">
            <TrainingForm on:calculate={(e) => handleCalculate(e.detail)} />
          </div>
        </div>
      {:else}
        <div class="resultSection">
          <ResultDisplay {result} />
          <button class="resetBtn" on:click={resetForm}>
            ← 返回重新计算
          </button>
        </div>
      {/if}
    </div>
  </main>
  
  <footer class="footer">
    <p>科学训练，健康运动 | 数据仅供参考，请根据身体实际情况调整</p>
  </footer>
</div>

<style module>
  .app {
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    background: linear-gradient(135deg, #f0f4ff 0%, #faf5ff 100%);
  }
  
  .header {
    background: linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%);
    color: white;
    padding: 2rem 1rem;
    text-align: center;
    box-shadow: 0 4px 20px rgba(79, 70, 229, 0.2);
  }
  
  .headerContent {
    max-width: 800px;
    margin: 0 auto;
  }
  
  .logo {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.75rem;
    margin-bottom: 0.5rem;
  }
  
  .logoIcon {
    font-size: 2.5rem;
  }
  
  .title {
    font-size: 2rem;
    font-weight: 800;
    margin: 0;
    letter-spacing: -0.02em;
  }
  
  .subtitle {
    font-size: 1.05rem;
    opacity: 0.9;
    margin: 0;
  }
  
  .main {
    flex: 1;
    padding: 2rem 1rem;
  }
  
  .container {
    max-width: 700px;
    margin: 0 auto;
  }
  
  .card {
    background: white;
    border-radius: 20px;
    padding: 2rem;
    box-shadow: 0 10px 40px rgba(0, 0, 0, 0.08);
  }
  
  .formSection {
    animation: slideUp 0.5s ease;
  }
  
  .resultSection {
    animation: fadeIn 0.5s ease;
  }
  
  .resetBtn {
    margin-top: 1.5rem;
    padding: 0.875rem 1.5rem;
    background: white;
    color: #4f46e5;
    border: 2px solid #4f46e5;
    border-radius: 10px;
    font-size: 1rem;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.2s ease;
  }
  
  .resetBtn:hover {
    background: #4f46e5;
    color: white;
  }
  
  .footer {
    background: #1f2937;
    color: #9ca3af;
    padding: 1.5rem 1rem;
    text-align: center;
    font-size: 0.875rem;
  }
  
  .footer p {
    margin: 0;
  }
  
  @keyframes slideUp {
    from { opacity: 0; transform: translateY(20px); }
    to { opacity: 1; transform: translateY(0); }
  }
  
  @keyframes fadeIn {
    from { opacity: 0; }
    to { opacity: 1; }
  }
  
  @media (max-width: 640px) {
    .header {
      padding: 1.5rem 1rem;
    }
    
    .title {
      font-size: 1.5rem;
    }
    
    .subtitle {
      font-size: 0.95rem;
    }
    
    .card {
      padding: 1.25rem;
    }
    
    .main {
      padding: 1rem 0.5rem;
    }
  }
</style>
